Update build script, and fix build warning

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,10 +4,9 @@ on:
   push:
     branches:
       - master
+    tags:
+      - 'v*'
   pull_request:
-  release:
-    types:
-      - published
 
 env:
   DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
@@ -33,21 +32,26 @@ jobs:
       - name: Test
         run: dotnet test -c Release --no-build
       - name: Pack
-        if: matrix.os == 'windows-latest' && github.event_name == 'release'
+        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
+        shell: pwsh
         run: |
-          arrTag=(${GITHUB_REF//\// })
-          VERSION="${arrTag[2]}"
-          VERSION="${VERSION//v}"
-          echo Version: $VERSION
-          dotnet pack -c Release -p:Version=$Version -p:PackageVersion=$VERSION -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$Version -o nupkg src/CsvTextFieldParser/CsvTextFieldParser.csproj
+          $GITHUB_REF = $env:GITHUB_REF
+          if (!($GITHUB_REF -match 'refs/tags/v(\d+\.\d+\.\d+)')) {
+              Write-Error "Failed to parse version from GITHUB_REF: $GITHUB_REF"
+              exit 1
+          }
+          $Version = $matches[1]
+          Write-Host "Version: $Version"
+          & dotnet pack -c Release -p:Version=$Version -p:PackageVersion=$VERSION -p:AssemblyVersion=$Version -p:FileVersion=$Version -p:InformationalVersion=$Version CsvTextFieldParser/CsvTextFieldParser.csproj
+          exit $LastExitCode
       - name: Upload Artifact Nupkg
-        if: matrix.os == 'windows-latest' && github.event_name == 'release'
+        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
         uses: actions/upload-artifact@v2
         with:
           name: nupkg
           path: ./CsvTextFieldParser/bin/Release/*.nupkg
       - name: Upload Artifact Bin
-        if: matrix.os == 'windows-latest' && github.event_name == 'release'
+        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/v')
         uses: actions/upload-artifact@v2
         with:
           name: bin
